### ISSUE TITLE
Scrolling though Elder Scrolls

### ISSUE THREAD

**Issue by JeremyF5737** [newtfire/digitProjectDesign-Hub#11]
### Proposal

Hello this is Jeremy Fischer, And i have a proposal for a project involving the study of books in the Elder-Scrolls video game series. In the Elder-Scrolls there are books, scrolls, and notes as items but are categorized in the players inventory as books in a different tab. These books can actually be read (except spellbooks) to learn about the lore of the world known as Tamriel or offer improvement of skills such as an increase in the persuasion skill in later games. Some of these books are about as thick as 1 inch within the game, but the player can read at most 3-6 pages from an average book, which is assumed to be just relevant information. 
![image](https://user-images.githubusercontent.com/70647839/93224374-08271200-f73f-11ea-913e-89730fbd7780.png)

The project would be similar to the "Eldritch Project" and the "Bloodborne project" except it would be organized in a quantifiable manner for the item size to the amount of words, keywords, adjectives, and if the information is of any use inside of the game. All of these books can be found within the game, and can be created using the in-game console by typing an item-code.

### Organization

For example there is a book in one of the games TESV: Skyrim that is called _Antecedents of Dwemer Law_ and this is how it would be structured in a table.

- title of book

- part of a book series

- game appearances (Morrowind, Oblivion, Skyrim)

- related to a quest (yes (quest name) or no)

-  Item Code (0001B22F)

- Player Acquisition (found, purchased, or by ingame console)

- Fictional character author (most are unknown in the case of the Dwemner race)

-  Type of book (hardback (tattered), harback (noble), scroll, papyrus note, leather journal, etc)

- How many pages in-game

- number of words within book

- Mention of deities (integer)

-Mention of races (integer)

- Mention of continents (Hammerfell, Skyrim, Morrowind, Cyrodill, Valenwood)

- In-game stat boost on opening book (yes (stat that is increased) or no)

- number of adjectives within book

- contents link : https://elderscrolls.fandom.com/wiki/Antecedents_of_Dwemer_Law

### What is to be accomplished from this project

The project would aim to make a database for any player of these games on where to acquire and if it worth acquiring in game depending on the information. If the player wanted to learn about lore without collecting the hassle of these in-game items, they could read the contents in order from the project page, maybe even with a simplified translation from the "fantasy language" to a simplified version created by a student. The table would eventually lead to show statistics tables of how many pages/words are broken up between the book type, how many adjectives are in each book type, and any more interesting statistics that people can come up with. With this project the aim is to make reading the contents of the lore books easier for players to organize and be thoroughly read on a website and to be compared with other books the player does not already possess.

**Comment by MasonG27** [comment]
I love this idea Jeremy, as a long fan of the elder scrolls series I have had my fair share of late nights looking into the lore of this game both in game and out. Skyrim is easily my favorite game in the series but what I love is that the world and lore connect all the games together through the books. That is actually how I learned most of what i know about the other games. Im not sure if your plan is to do one book or multiple but if you were to do one I would definitely suggest focusing on one that brings all the games together.
When it comes to suggestions I do not have a whole lot as you seem to know what you want to include in your project and obviously with this one you can go all out. I think the only one suggestion i have for you were would be suggesting the inclusion of the book series/volume association. Overall I look forward to this project hopefully getting started!

**Comment by Joelpie** [comment]
I've been a fan of Skyrim for a while, but have never delved very deep into the lore found in the game's written material. I'd love to see this thing get started, and would also enjoy helping out. I feel like the depth of Skyrim's lore is not to be underestimated, but carrying out this project would be an awesome learning experience.
