### ISSUE TITLE
Recipes (vs. Potter)

### ISSUE THREAD

**Issue by beealex** [newtfire/digitProjectDesign-Hub#13]
Hello, my name is Bianka Alexander and for my project proposal I was thinking of analyzing various aspects of the Harry Potter series. Would it be enjoyable? Yes! Would I geek out over it? Probably. But, it would also give more insight to those who are unfamiliar with the series. I would love to focus on character archetypes, horcruxes, the deathly hollows, maybe a relationship tree, as well as the books inspiration from legends and languages. ***While all of these would be my ideas, not all of the larger aspects may be feasible to accomplish in a single semester.

Organization
- Background info of book and overall set up for the series
- Character archetypes
	—> analysis of the main characters and their relationship to a literature based archetype
	—>include the character mentions in a single book
- Horcruxes
	—> analysis of horcruxes and their significant meaning to the series
- Deathly Hollows
	—>Incorporate the Tale of the Three Brothers
		—> Possibly include base inspiration 
- Relationship Tree
	—> Incorporate Pictures 
	—> Description of character and their role, house, etc.
	—> Maybe incorporate critical mentions 
- Timeline of Events
- Simplified Spell Book and the inspiration for them

On the other hand, I also have a few interesting ideas for a project on ancient recipes! I feel like the ancient recipes would be really cool to do for this semester as it would involve historical research. I would prefer to do the recipes for DIGIT 400. This would make it challenging enough as a semester/ year long project and wouldn’t be too overwhelming on top of a senior project. With that being said, I think the Harry Potter Project would be cool as a personal senior project (if possible).

**Comment by ebeshero** [comment]
@beealex One of the issues with working on Harry Potter is that the author and affiliated lawyers are notoriously fierce over protecting copyright over reproduction of the text. The Harry Potter study I posted for discussion could run because they worked with only the text of one chapter or a short portion of the novel to do a close-up detailed linguistic study of how much Google Translate would alter it moving into different  language systems (say English to Polish and back into English). 

I recommend a topic based on the digital availability of its source texts for fair use and reproduction and adaptation using markup. Try to work with texts not bound by copyright restrictions for this project. So the historic recipes topic is definitely a safer call here. @beealex

**Comment by ebeshero** [comment]
@beealex That said, I just discovered, thanks in part to your code for Relax NG 3, that all the Harry Potter Screenplays are openly available for research and educational purposes online: https://bulletproofscreenwriting.tv/happy-potter-screenplay-download/ You're student researchers, so I think we could definitely do something with the screenplay material!

**Comment by beealex** [comment]
@ebeshero So does that mean that my HP Project would be available to do as long as the screenplays are used? Also, since the intention wasn't to reproduce the whole book, just use a chapter or small excerpt when necessary-- similar to the linguistics HP Project-- would that be feasible (if this project came to light)? For the portion of the project that requires analysis of characters/objects, I was thinking it could be handled like an AP Lang situation.

**Comment by fammysillar** [comment]
Hi! I am also interested in the recipes, the additional ideas I came up with were:
- Focus on a couple countries
- Focus on a specific time period
- Compare the differences between ingredients/spices/methods
- Use graphs or other graphics to represent the data 
(:

**Comment by ebeshero** [comment]
@beealex Yes, I think you could do this if you're working with the screenplays. You'd want to be organizing info from the Harry Potter world based on your markup of the plays. So, to study the archetypes, for example, you'd want to work with complete files I think rather than a small portion.
