### ISSUE TITLE
Exploring and Analyzing the K-Pop Genre

### ISSUE THREAD

**Issue by PiperBaron** [newtfire/digitProjectDesign-Hub#14]
## Proposal

Hello! As we’ve gone forth with our different XML and Relax NG assignments, I’ve found myself going back to song lyrics again and again -- I just find it really fun! I think lyrics are perfect for this kind of project, they’re so neatly organized into different sections and there’s so much information to pack into different elements/attributes. I thought marking up songs from a particularly prolific artist/group or even from a whole genre would be a worthwhile project, especially if that artist/genre is lesser known and could use more exposure. 

Although I’m open to just about any group, genre, subgenre, etc., I was thinking that analyzing [K-pop](https://www.vox.com/culture/2018/2/16/16915672/what-is-kpop-history-explained) lyrics would be an interesting direction to take. It’s a very unique and niche kind of music in the west, and this project could help demystify it and add cultural context to the music/lyrics. I also think K-pop would be particularly perfect for this project, because most groups have 5 or more members, who all have different roles and responsibilities in regards to lyrics (vocals vs rapping, that kind of thing), giving us a lot of additional information to work with in terms of analysis and display. Not to mention the fact that there are many, _many_ groups, who all fall under unique categories of their own (girl or boy group, number of members, “generation” or debut year, genre/conceptual focus, etc.) You can reference any given [lyric video](https://www.youtube.com/watch?v=cPwzLzy97L8) to see how every member of a group will have at least a few lines, and read through [a wiki](https://kpop.fandom.com/wiki/Stray_Kids) to see the organization of groups with their particular roles and possible subunits.

Obviously most K-pop lyrics are in Korean, which would present a unique kind of challenge with markup. I think that fact makes this project even more interesting, but we could compromise and use reliable English translations of the lyrics if anyone is uncomfortable with working on text in a foreign language.

The exact scope of this project is totally up for discussion. There are individual groups like BTS and EXO who have discographies of hundreds of songs that we could focus on, or we could go broader and only take the most popular few songs from a handful of groups (or maybe even focus in on a specific genre, like K-pop/Rap or K-pop/Rock). Additionally, like I said above, this project does not have to focus solely or even at all on K-pop, it’s just an example of a kind of music that might work really well with what we’re trying to do. 

### Organization
I did a sample song for our third Relax NG assignment, which you can view [here](https://github.com/PiperBaron/Digit400-PiperBaron/blob/master/Regular.xml), just to give a basic outline of what exactly a given song might look like. 

It’s broken down into separate sections:
- About
    - Background info on the song itself
    - The group who does the song
    - A list of every member, adding in roles (dancer, rapper, etc.) and relevant pieces of information
    - Name of the album it belongs to (or specifying if its a single)
    - Composer/producer credits
    - Release date
    - Label/Company
    - (Optional) Current number of [music show wins](https://www.soompi.com/article/1220849wpp/guide-music-show-wins-need-know)
- Lyrics
    - Intro (if there is one), Verses, Choruses, Pre-Choruses, the Bridge, and Outro (again, if there is one)
       - All of these elements will be numbered and contain the individual lines sung/rapped/spoken, with a reference to the xml:id of the member(s) performing them

As for data analysis, I think there are many directions we could go. One standout point of analysis would be [line distribution](https://biaswrecker.com/these-are-20-of-the-absolute-worst-line-distributions-in-k-pop/) (how many lines one person in a group gets to sing/rap versus another), an already popular topic within K-pop fan communities. We could also analyze word choice, song structure, composing/producing credits (some idols are composers on top of being in a K-pop group, so adding composer credits might be interesting to display which groups produce their own music and those who don’t), etc. If we expand the scope beyond one group and into the wider range of K-pop in general, we could also analyze the frequency of certain genres/subgenres or the popularity of a group’s songs/albums (based on sales/views/wins).

### What’s the point?
As said previously, there’s still a lot of mystery and misinformation surrounding K-pop (some of it due to genuine confusion, some of it due to racism), and I think this project could help in educating people on the topic and expose them to a wider-range of music. There’s a lot of cultural context and background information that could be added here, where we could discuss the deeper meaning of lyrics (all of which will be taken from native-speaking Koreans who’ve posted their thoughts on other platforms with proper credit given), and (if we do include translations) provide non-Korean-speaking people with lyrical meaning for K-pop songs. Plus, I just think it’d be a lot of fun. :)

**Comment by JeremyF5737** [comment]
I like the idea of the project and the exposure of the kpop scene of music. I think an important feature to include in the organization is the translation from the Korean sub to the English dub of the song, because most bilingual songs with an English version and a foreign language version are not exactly word for word when the group translates over. This seems like a promising project, it would assist the understanding of other genres effect on kpop music from other perspectives, and be a gateway for someone to consume the music they create. I would be interested in working on this project in the future.
