### ISSUE TITLE
The Progression of James Bond Films and Music  

### ISSUE THREAD

**Issue by zteyssier** [newtfire/digitProjectDesign-Hub#15]
[**Proposal**](url)

Hello everyone!  This project would analyze the evolution of the character, James Bond, as well as the evolution of the music associated with each film.  The purpose would be to compare the different versions of Bond portrayed by Daniel Craig, Roger Moore, Sean Connery, Pierce Brosnan, Timothy Dalton, David Niven, George Lazenby.  The lyrics, instrumentation, artists, and themes will be compared to help understand the James Bond franchise in a new light.  This could help us understand the culture, standards, and expectations in the 1970s for example.

![Skyfall](https://user-images.githubusercontent.com/70618741/93530825-386fdb80-f90c-11ea-80a7-84bd7ca4495b.jpg)

**Organization**

_Portrayals_ 
      - Provides a few paragraphs on each actor and the version of James Bond that is portrayed.
      - The films will be listed with each actor as well as the duration of each portrayal.  

_Soundtracks_
      - Each intro song will be analyzed first with appropriate XML markup. 
      - Here is a Spotify playlist with all of the [Intro Songs](https://open.spotify.com/playlist/5fXfad3KG0rB3F6ZwdeEov?si=Sc2rhaYETXevkAndHsMQKg)
      - The lyrics can be found on the music website, [Genius](https://genius.com/)
      - Comparisons can be made to discover similar themes in lyrics as well as in instrumentation with motifs.  
      - Soundtracks that do not include lyrics can be analyzed as well to discover mood, themes, and exactly how the pieces fit into the film and the character of James Bond.  

_Text Comparison_
      - Frequency of text or phrases can be provided through programs such as Voyant.  Charts or graphs can be made through Excel or another software program.  

_Essay:  Evolution of James Bond_
      - This can be a short essay analyzing and providing insight into how James Bond has evolved in Pop Culture.  
      - This could be interactive for the user.
      - Soundbites from interviews with some actors can emphasize points in the essay.  Soundbites that include film music, will help illustrate the tone, mood, and ambiance for each story within the franchise.   

**Remarks**

There are probably other directions to take this project.  I think this would be interesting to see how (or if) each film influenced a particular decade.  I am curious to hear your feedback.

Thank you for your time.

**Comment by ebeshero** [comment]
Just a quick comment: I'm glad you're thinking ahead about charts and graphs! You'll be learning how to work with XPath and XSLT, possibly XQuery on your projects to pull data from your markup and plot patterns in a way that's easy to share and view over the web: so you'll be writing some code that remixes your XML code into HTML and SVG (scalable vector graphics, generated in XML syntax)!
