### ISSUE TITLE
Discography Analysis on Band/Artist of Choosing

### ISSUE THREAD

**Issue by CTrohoske01** [newtfire/digitProjectDesign-Hub#16]
When we all discussed what we were interested at the start of the semester most of us shared a common thread of music. Looking at past student projects there was one that stuck out to me that analyzed the progression of the music of a band and their discography. Personally I love classic rock/folk/pop and would love to see if anyone else shares the same interest. This could range from The Beatles, to Bob Dylan, to Led Zeppelin, etc. 

The main goal of this project would be to take the entire discography of whatever band/artist we choose and analyze how the band progressed and changed throughout their career. Song structure, lyrics, band members, etc. would all be important in this process. We could then take these findings and raise particular questions about possibly why these changes occurred. Were there important historical events that shaped certain periods? Did the evolving culture help shape the themes that these artists discussed?

Organization:

-Lyrical Analysis: I think this would be the most crucial part of the project. This would would lyrical themes, the changing mood of different albums, word choice, etc.

-Song Structure: This would be another crucial part of the analysis. This would explore how the band/artists songwriting and construction of songs changed or not changed. It could take into account overall song lengths, albums lengths, complex/less complex song structure. 

-Band Changes: Looking into band structure, whether that changed or stayed the same throughout their career. This would look into if there were band member changes, production crew changes, etc.

Conclusion:
I think this could be a really fun and enjoyable project. Many of us shared our interest in music at the beginning of the semester so I thought this could be fitting! Feel free to comment if you're interested and share some of your favorite band/artists!

**Comment by PiperBaron** [comment]
I'm really interested in working with music in some way for this project, so if not my own idea, I'd love to work on this one! I really like that you included exploring the themes and historical context for the lyrics -- that would be so fascinating to analyze/graph/chart however we could. I'd also be open to working with whatever artist the group would like, although I personally think that The Beatles would be perfect for this kind of analysis. I'm really looking forward to seeing where this project would go if it gets chosen by enough people.

**Comment by CTrohoske01** [comment]
@PiperBaron @dpakulski42 seems like we all kind of share a common interest here. Would you guys be interested in possibly grouping up and ironing out some ideas!

**Comment by zteyssier** [comment]
This seems like an interesting project!  It seems like we are all fixated on music. @CTrohoske01 @dpakulski42 I have a deal to propose as well.  We could use @CTrohoske01 (your) idea to analyze the bands and artists for each of the James Bond intro songs.  Blues has inspired a majority of the intro songs so we could work that in as well!  @dpakulski42 The intro songs are usually ballads that describe the feeling and foreshadow the plot of the films.  Let me know what you think.  Thanks!
