### ISSUE TITLE
Mapping the History of Blues Music in the United States

### ISSUE THREAD

**Issue by dpakulski42** [newtfire/digitProjectDesign-Hub#17]
Proposal

This project would be the mapping and tracking of the history and evolution of blues music in the United States. Blues music is inextricably tied to the history of the United States. It’s influence on music is still prevalent to this day. This project would follow that influence by tracking it out over a map. This would help us further understand it’s influence and give us context on its importance to all of music.

Organization

Mapping: Map of US with dots where important events and individuals have appeared
Tracking: Lines linking these and tracking how they’ve travel across the country
Evolution: Line indicating change in style and how that style spread
Details: Paragraphs with info about significant points and people

Remarks

Born out of one of America’s great tragedies, blues music has evolved ever since the late 1800’s and has taken many forms such as rock and soul music. Tracking this undeniable influence would be enlightening on our culture and music.

**Comment by CTrohoske01** [comment]
The proposal is one that is related to mine and one I would definitely be interested in working on. I think we could tie my idea into this somehow since some of the bands/artists I mentioned in my proposal were heavily influenced by the blues.
