### ISSUE TITLE
The History of American Cosmetics 

### ISSUE THREAD

**Issue by fammysillar** [newtfire/digitProjectDesign-Hub#19]
Hi! I'm Sammy Fillar and I am Interested in doing my project on the history and evolution of make up in the United States beginning around the 1900's. I got my inspiration from watching this video: 
https://www.youtube.com/watch?v=g08-_NExOX0
Topics would include:
- Origins of styles accompanied by who used them.
- Origins of why products were made/ What their purpose was
- Digital renditions of how the makeup in a certain period was applied/ application
    - Lists of what was used on the face/body (and if it is still available or in use today)
Organization:
I would plan on having different tabs such as "origin history" "product list(by decade)" "timeline". I also would like to incorporate images from a base model that I would be able to photoshop what is on the face at certain times, to easier show what is being described. I would also like to include a map if possible to show where these trends were taking place.

**I am also interested in the ancient recipe idea that was brought up**

**Comment by ebeshero** [comment]
@fammysillar For our XML-based projects, you'll want some source documents to mark up that will help to provide something you can analyze and explore about the history of cosmetics. I like the idea of this, and I suspect you can re-shape it depending on what kinds of collections you locate. Here are a couple of suggestions for web resources that might give you a basis for markup on make-up (haha, see what I did there?):

* In-cosmetics connect (lots of info here about cosmetics ingredients, for example): https://connect.in-cosmetics.com/  

* Stats and info on the Cosmetics industry: https://www.statista.com/topics/1008/cosmetics-industry/ 

* Smithsonian archives on historical cosmetics (browse around here, and notice they've got a curated collection of images: What could you do with images and maybe related documents about cosmetics): https://www.si.edu/spotlight/health-hygiene-and-beauty/make-up 

This is one of those topics where *you* would need to provide structure for the project. So this would require the team to do some careful thinking and planning to work out. Every team will need to do this, really, as you work toward a project schema.

**Comment by beealex** [comment]
Hi Sammy! I am also interested in the recipe idea and have a couple of ideas for that project! I think you/we could get some background info on history regarding types of dishes/main spices used in each country and include a map of trade routes (if applicable/possible). This would make the project more in-depth and provide more insight into the importance of recipe history.
