### ISSUE TITLE
Adding Hub Collaborators

### ISSUE THREAD

**Issue by PiperBaron** [newtfire/digitProjectDesign-Hub#2]
My username is @PiperBaron. @ebeshero please add me as a collaborator to this DHClass-Hub.

**Comment by ebeshero** [comment]
@PiperBaron I've added you! Welcome, the first of our DIGIT project design class members! :-)

**Comment by beealex** [comment]
My username is @beealex. @ebeshero please add me as a collaborator to this DHClass-Hub.

**Comment by dpakulski42** [comment]
My username is @dpakulski42. @ebeshero add me as a collaborator!

**Comment by zteyssier** [comment]
My username is @zteyssier. @ebeshero, please add me as a collaborator to this DHClass-Hub.

**Comment by AreannaRussell** [comment]
My username is @Russell. @ebeshero please add me as a collaborator to this DHClass-Hub.

**Comment by Joelpie** [comment]
Hello, my username is @Joelpie. @ebeshero please add me as a collaborater to this Hub.

**Comment by fammysillar** [comment]
Hi! my username is @fammysillar. @ebeshero please add me as a collaborator to this Hub.

**Comment by ebeshero** [comment]
@fammysillar @Joelpie @AreannaRussell @zteyssier @dpakulski42 @beealex @PiperBaron Welcome to our digitProjectDesign-Hub! I've sent each of you invitations to join that you'll need to confirm your membership and gain "push-access" to this repo!

**Comment by ebeshero** [comment]
@fammysillar @Joelpie @AreannaRussell @zteyssier @dpakulski42 @beealex @PiperBaron  So, check your email to confirm!

**Comment by CTrohoske01** [comment]
Hi! my username is @CTrohoske01. @ebeshero please add me as a collaborator to this Hub

**Comment by Tricky-Keys** [comment]
Hi! my username is @Tricky-Keys. @ebeshero please add me as a collaborator to this Hub.

**Comment by elmusfi** [comment]
Hello, my username is @elmusfi. @ebeshero please add me as a collaborater to this Hub.

**Comment by ebeshero** [comment]
Hi there, @elmusfi ! I've just sent you an invitation: Go check the email you used to set up your GitHub account, and accept my invitation to join. :-) Welcome!!! :-)
