### ISSUE TITLE
Analyzing a Game Design Document

### ISSUE THREAD

**Issue by MasonG27** [newtfire/digitProjectDesign-Hub#20]
**Proposal:** 

For this project I would love to go in the direction of doing an analysis on a game design document/pitch. I am not completely certain whether I would want to focus on something I have developed in the past or one that is more developed from a known game however, I think both would be very interesting and fun. Since I have been involved in game design in the past 2 years, I learned a lot about game design documents, and I find them really intriguing in how detailed they get, as well as their huge importance in the industry and the success of the development process. I think it would be very useful to actually incorporate a GDD into an xml project and see what the results are and I'm sure I would learn a lot about how to better structure a future game design document. I will use this as some kind of reference as this has a good mix of structure to it. This is a pitch (announcement/showing of the game and its mechanics) of the original bioshock game.              https://www.systemshock.org/index.php?PHPSESSID=iide3g3h7i1cb58gj7dcn1jgjo;topic=2121.msg21031#msg21031 

 

**Organization:** 

_TOC_: Table of contents is always an important part to incorporate for ease of use. 

_Overview_: Giving the best overview of the game will make or break the games interest.  

_Gameplay_: The mechanics of the game would be explained and shown in this section. (This will contain the most amount of attributes and elements by far) 

_Backstory_: Including the story part of the game would be a nice switchup from the list style that most of the document would consist of. 

_UI_: Interface of the game will contain a lot of images but also plays an important role for visual information. 

_Why_: Giving an overview at the end will provide additional information to close out the document. 

 

**Reason:** 

I would really enjoy doing a project on this because one of my favorite parts about game design is the learning curve of it which mostly includes figuring out great, unique mechanics that work consistently and that is hard to find nowadays. Which is why we are seeing so many remasters and remakes as well as easy money-making schemes like in game microtransactions instead of creating new and interesting ideas. I want to help myself learn more about the making of game design documents and I think structure plays an important role and creating an xml documentation on one would really reveal a lot.

**Comment by CodyCarlson17** [comment]
I really like this idea and it goes along the same path of what I suggested for a project. There is a lot that can be learned and seen with a video game, whether it is your own or someone else's game. It would be fun to dive into a great game or create one for yourself. It is very true that a lot of today's games are filled with micro-transactions and not solely focused on the performance of the game. One thing that I would recommend is to try and find something that you want to focus mainly for the game. For example, looking at the artwork in the game or the music in the game. Something that you can track and create a script for would be ideal. Overall, I think that this project would be awesome to do and would be fun to dive into it as well.

**Comment by elmusfi** [comment]
I am very interested in this idea also. It would be great to break a game down and take a look at its core components, it's also helpful to see what parts may be making or breaking this game, and what someone would be interested in keeping or building upon in their own game. Overall great project proposal!
