### ISSUE TITLE
Newtfire Website Links

### ISSUE THREAD

**Issue by elmusfi** [newtfire/digitProjectDesign-Hub#26]
Hi everyone! At the bottom of the HTML 1 Exercise page, it mentioned an issue to paste our Newtfire website links once they're live for everyone to view. Since there isn't one from what I see, I decided to make one here. 

Here is my website, ready to view!

https://newtfire.org/~erw32/

**Comment by ebeshero** [comment]
@elmusfi Oops! I forgot to post it! Thank you for starting this issue. :-)

**Comment by AreannaRussell** [comment]
https://newtfire.org/~acr5402/

**Comment by beealex** [comment]
https://newtfire.org/~bca5125/

**Comment by CTrohoske01** [comment]
https://www.newtfire.org/~cmt5864/

**Comment by dpakulski42** [comment]
https://newtfire.org/~dxp320/

**Comment by PiperBaron** [comment]
https://newtfire.org/~pub81/

**Comment by zteyssier** [comment]
https://newtfire.org/~zat5030/

**Comment by MasonG27** [comment]
https://newtfire.org/~mxg5661/

**Comment by JeremyF5737** [comment]
https://newtfire.org/~jjf5737/
