### ISSUE TITLE
Requests to be added as a Collaborator on This Repo

### ISSUE THREAD

**Issue by ebeshero** [newtfire/digitProjectDesign-Hub#35]
Please post here to introduce your GitHub self to our Fall 2021 DIGIT 400 class, and  request to be added as a collaborator on this repo!

**Comment by austinmurry** [comment]
My username is @austinmurry. Please @ebeshero add me as a collaborator on this Hub.

**Comment by amayadwillis** [comment]
my username is @amayadwillis, please add me to this repo

**Comment by wdjacca** [comment]
my username is @wdjacca:) Please let me collaborate here:)

**Comment by bwm5473** [comment]
Mt username is @bwm5473. May I please be added as a collaborator on this repo?

**Comment by am0eba-byte** [comment]
HELLO I am @am0eba-byte and it'd be pretty neat if I was added as a collaborator to this repo

**Comment by Kennaab** [comment]
My username is @Kennaab, please add me to this repo

**Comment by amw6765** [comment]
my username is @amw6765, please add me to this repo

**Comment by san5281** [comment]
Hello I am @san5281 add me or I will be a sad panda :(

**Comment by BarbieCessar** [comment]
Hello my username is @BarbieCessar please add me to this repo! :)

**Comment by Scarlett-Lion** [comment]
Hello my username is @Scarlett-lion please add me to this repo

**Comment by Tiny-Pickles** [comment]
Hi I am Grace and my username is @Tiny-Pickles, please add me to this repo. Thanks!

**Comment by Emily-Levi** [comment]
I'm Emily my username is @Emily-Levi please as me to the repo

**Comment by ebeshero** [comment]
I've now invited everyone to this repo who has posted a request as of 11:23pm ET on Thurs. 9/2.

**Comment by N00000DLE** [comment]
my username is @N00000DLE Please let me collaborate here:) (Destinee)

**Comment by GHess09** [comment]
This is Garrett Hess, my username is @GHess09, please add me as a collaborator.  Thanks!

**Comment by sxa585** [comment]
> Please post here to introduce your GitHub self to our Fall 2021 DIGIT 400 class, and request to be added as a collaborator on this repo!

**Comment by Cameron-Bigi** [comment]
Please add me username is Cameron-Bigi

**Comment by AtomicOlsen** [comment]
Please add me as a collaborator to our DIGIT400 hub. @AtomicOlsen

**Comment by Beeplosion** [comment]
I think I messed up my request earlier so my username is @Beeplosion

**Comment by ebeshero** [comment]
Each of you has now received an invitation to join the digitProjectDesign-Hub! Check the email you used to set up GitHub for an invitation. (Check your web profile on GitHub for details if you don't remember what email you used.) If you were already a member of the newtfire organization of GitHub repos, you might have just been automatically added, too.
