### ISSUE TITLE
Project Proposal: Civil Rights 

### ISSUE THREAD

**Issue by Tiny-Pickles** [newtfire/digitProjectDesign-Hub#44]
I was thinking about creating a digital project that encompasses the important documents or legislation that relate to the Civil Rights movement. I was thinking about creating an interactive timeline of the documents and/or an interactive map that chronically shows the progress of civil rights. All documentation would be from significant events that occurred during the civil rights movement like legislation passed at the federal/state level as well as court cases.

If possible I would like to include some first hand accounts of peoples' experiences during the civil rights movement. (primary sources)

Please let me know what you think and if you could elaborate on this idea more. 

Here are some links for some source materials for this project. 
https://www.ourdocuments.gov/content.php?flash=false&page=milestone
http://crdl.usg.edu/?Welcome

I found some primary sources from African American slaves that were still living in the 1930s. Probably could use the source listed below for many of the documents because it is from the library of congress. 
https://www.loc.gov/collections/slave-narratives-from-the-federal-writers-project-1936-to-1938/about-this-collection/

**Comment by Tiny-Pickles** [comment]
I found some primary sources from African American slaves that were still living in the 1930s. 
https://www.loc.gov/collections/slave-narratives-from-the-federal-writers-project-1936-to-1938/about-this-collection/

**Comment by sxa585** [comment]
Get pranked grace

**Comment by sxa585** [comment]
Get pranked again grace

**Comment by N00000DLE** [comment]
Hi Grace! I think this project sounds fascinating! It would be really cool to look at a lot of the Civil Rights movement documents and possibly compare them to pre-civil war era documents. I really enjoy history and anything to do with civil or human rights, so I would love to see this project done!

**Comment by amw6765** [comment]
This project sounds super cool! I necessarily would not wanna work on this topic myself, however, this proposal has the structure and beginnings for a great project. Being able to visualize the timeline of civil rights and its progress throughout the years in the US could help others to see just how long and hard people have been fighting for equality. And as you stated, I would definitely emphasize the key leaders in the civil rights movement and their accomplishments. Great project idea! If selected this will be quite fascinating to see get put together.
