### ISSUE TITLE
Project Proposal: Behrend Trees

### ISSUE THREAD

**Issue by N00000DLE** [newtfire/digitProjectDesign-Hub#47]
I was thinking of creating a interactive map project based on the labeled trees around campus. These trees have always interested me and the story behind how they got to Behrend. Sort of like the map we looked at in class but a lot more simple. Possible a Behrend map with all of the trees as icons on the map that are clickable. When you click a tree information pops up on it and then you can open up a more extensive page if you want. Then this site doubles as informational and as a map on where to find the trees.

For the XML I thought we could use resources online/from the library to find information on the type of trees they are and possibly even some background on how the trees got to Behrend.
Some possible sources for tree information:
BASIC MAP OF TREES: https://behrend.psu.edu/about-the-college/the-arboretum-at-penn-state-behrend/arboretum-walking-tour-and-list-of-trees
https://behrend.psu.edu/about-the-college/the-arboretum-at-penn-state-behrend
https://behrend.psu.edu/news-events/school-publications/school-science-publications/science-news-2016/map-trees

A source I found on how to make an interactive map in html:
https://codepen.io/mirichan/pen/jEBmyG

**Comment by am0eba-byte** [comment]
If this project ends up happening, I'm almost positive Dr. Sam Mason at the Sustainability Office at Behrend would LOVE to talk to you about getting the interactive photomap published on the Sustainable Behrend website (which is currently under construction)!

**Comment by amayadwillis** [comment]
I think this project idea is really interesting and I like how it would encourage people to get outside and go looking around more to take notice of the different trees we have on campus. I wonder if maybe once the site is built if you could convince whoever is in charge of stuff around campus (I have no idea who that would be) to let you put up little signs around the trees with a QR code people can scan to get sent to a page on your site about that specific tree.

**Comment by am0eba-byte** [comment]
I really like this project idea Destinee! I think creating this map of Behrend trees could also give rise to an informative section about why so many trees have been cut down at Behrend. You could make a section that describes the parasite that has plagued so many trees on campus, and I know Sam Mason would be very resourceful for providing more information on why even more trees have been cut down very recently for upsetting reasons... We must speak for the trees! I'd love to join this project if I don't get any bites on my project idea. (:

**Comment by Tiny-Pickles** [comment]
I think this would be a great project Destinee! I think you can add even more to this project by uploading actually images of the  trees and the leaves to compare and contrast the many different varieties that are grown at Behrend. Also you could add background information about the tree's origins and if they are local to PA. I would love to join this project if I can!

**Comment by GHess09** [comment]
I really love this idea!  I had a map idea in mind as well,!  For the past few years, walking around campus, I've always admired the different trees that we have.  I think this wood be a fun project that I would like to be a part of!  I'm a photographer, so I could also help getting nice images of them all!
