### ISSUE TITLE
Add me to the class github

### ISSUE THREAD

**Issue by CodyCarlson17** [newtfire/digitProjectDesign-Hub#5]
My username is CodyCarlson17 and I would like to be added to the group! :)

**Comment by MasonG27** [comment]
My username is MasonG27

**Comment by JeremyF5737** [comment]
My name is JeremyF5737 and i would like to be added to the group :D

**Comment by CTrohoske01** [comment]
My name is CTrohoske01 and I would like to be added to the group!
