### ISSUE TITLE
Project Proposal : Cars!

### ISSUE THREAD

**Issue by Kennaab** [newtfire/digitProjectDesign-Hub#50]
For this project, I was thinking about doing something to deal with cars. I would really love to take a deeper look into a specific car or different cars and their history. How they have changed over the years from their different models and specs. I would include images of the history and background information. 

Also would be cool to add maybe videos with the soundings of cars because they all sound differently over the years.

Possibly adding a section about basic car maintenance like changing oil, checking oil, changing spare tire, etc. Just a basic maintenance area on the page since the project would be about cars. Growing up, I have always worked on cars with my dad and have learned a lot. Sometimes people don’t have someone in their life to show them how to do basic car maintenance, which could save money and time. 

I have a lot of ideas about where this project could go but this is just a basic little summary.

https://www.history.com/topics/inventions/automobiles
https://news.jardinemotors.co.uk/lifestyle/the-history-of-car-technology

Specific car: https://www.nissanusa.com/experience-nissan/news-and-events/nissan-z-car.html

**Comment by ebeshero** [comment]
@Kennaab Here's the related proposal I  mentioned in class, connected to a proposal to get PSU Behrend involved in a new museum of automobile history! https://github.com/newtfire/digitProjectDesign-Hub/issues/40

**Comment by san5281** [comment]
Cars are cool so I am fascinated. Especially in the current year where a lot of youth don't know how to maintain their car (or in some cases, certain newer cars require expensive parts so you can't) so having an archive would be extremely useful. However, I do think that you are being a bit vague if you are going to go to the history of cars. For instance, Japanese brands like Toyota vs American brands like Ford evolved very differently and furthermore even brands from the same countries developed around different regulations from their time period (Chrysler vs Ford) and I think you will end up giving yourself a headache.

I would recommend doing one of two things. Either focus on a particular manufacturer and go on the history of cars or have a general knowledge archive on different types of cars (SUVs, automatic, manual, etc.) and how to maintain them. I am very interested!

**Comment by Kennaab** [comment]
@san5281 I was thinking about doing the project more on a specific car/brand, such as Nissan or Subaru. My brother actually has a 350z which has become very popular recently in the car community. I know up at Lake Erie Speedway they have drift events and there's quite a few 350z's or 370z's that drift up there. Not only with the drift events but they recently had Formula Drift up at Lake Erie Speedway, I figured it would be cool to add a little section about the speedway and the events that happen there. I do have some videos/pictures from the events.

I haven't really figured out all of the details yet of what I want to do lol. Just have always been passionate about cars

**Comment by san5281** [comment]
That would be really nice. Subaru's are very popular and is pretty popular amongst ricers due to how affordable older models are. They definitely have an interesting history!

**Comment by GHess09** [comment]
I do love cars, and am interested in this project.  I also have lots of friends and acquaintances in the car scene and that may come in handy?
