### ISSUE TITLE
Project Proposal: Guilty Gear Strive Soundtrack Analysis

### ISSUE THREAD

**Issue by trumerfe** [newtfire/digitProjectDesign-Hub#53]
For this project, I had the idea of analizing each song corresponding to a playable character in Guilty Gear Strive, utilizing xml markup to extractkey data from the songs, such as key words and verses. I would use this information to create interactive lyrics pages for each song, which show information such as which part of the song you are reading, which words or phrases are repeated often throughout the song, and explanations of the ties between the song and the character's backstory in the Guilty Gear universe.

**Comment by Beeplosion** [comment]
Really love this idea. Guilty Gear is one of my favorite series, and the music is always something neat to take a listen to. Analyzing lyrics to music is something I always found interesting, so I would be very interested in looking further into the music of GG. Maybe a comparison of some characters songs between games, showing off how their themes have changed, could be an interesting point.
