### ISSUE TITLE
Project Proposal: Ancient Mayan Temple/Artifact Modeling & Mayan Hieroglyph Analysis

### ISSUE THREAD

**Issue by am0eba-byte** [newtfire/digitProjectDesign-Hub#58]
**Ancient Mayans Digitized**

This project's final outcomes would be two-fold:

1. A digital text analysis of the English translations of ancient Mayan writing, which would involve working with images of Mayan hieroglyphics to display alongside the translations and analysis of the language on the website. There's a bajillion things we could do with these translations to make cool visualizations of their language usage, like how many times they referenced one of their Gods, which God they referenced the most, how many times human blood-letting and sacrifice was mentioned in their texts, etc. 

2. Using photogrammetry methods and 3D rendering software such as Blender to create digital 3D models of real ancient Mayan relics, artifacts, and parts of ancient Mayan human skeletons that have been discovered. OR, we could use a game-building software such as Unreal or Unity to recreate an ancient Mayan city to be embedded in the website. Or both.  
**EDIT:** We could totally take a project team field trip to museums in Pittsburgh, Cleveland, and Buffalo to go take pictures of the Mayan artifact displays they have! I'm also thinking about contacting a museum directly about the possibility of them letting us take the pictures, since we'll need to take a whole lot from many angles, and I imagine not all of their displays allow 360-degree viewing, or a glass box might be obstructing the shot.
 
This project idea is open to the input of interested patrons (: 

EDIT - I just thought of another possibility for this project: We could create a digital map of ancient Yucatan Peninsula (like the [Map of Early Modern London Project](https://mapoflondon.uvic.ca/agas.htm)) and code clickable locations and structures into the map, which on click would toggle a photo and description of the site/structure that the user clicked. So, basically the same exact concept as MoEML, except instead of London it'd be the Yucatan Peninsula as it was during the ancient Mayan civilization's peak.

Edit Pt. II - We could also implement the use of a timeline into the map^ (or alone)  to display the rise of the ancient Mayan civilization, the tools, tech, art, and structures they developed through time, what a Mayan city looked like at the civilization's peak, and then finally their downfall.

ALSO, there's a possibility that we could animate some ancient Mayan illustrations that were drawn on pottery and other objects!!! Which would be super cool and fun.

Resources:

Dr. B's spouse Dr. Greg Bondar, who I'm sure would love to show us some Mayan hieroglyph translations and possibly let us use some of the Mayan artifacts he has to let us do photogrammetry magic on them to turn them into 3D models

[This neat website I just found](http://www.famsi.org/research/pitts/index.html)

[Wikipedia is cool](https://en.wikipedia.org/wiki/Maya_script)

[A neat example of using Unreal Engine for Archaeology](https://youtu.be/wNjGwRM2ZUU)

**Comment by ebeshero** [comment]
@ghbondar Would you like to comment on this fascinating proposal?

**Comment by bwm5473** [comment]
This sounds like an idea that I might be interested in joining.
If you plan on doing photogrammetry on whatever artifacts you find, were you going to taking photos of every angle of them with your phone, or were you going to try and find access to a 3D scanner to scan them directly?

**Comment by am0eba-byte** [comment]
@bwm5473 I was thinking we could just take a bunch of photos of each artifact to send through Meshroom to create the model, like what we did in DIGIT 409! I've never used a 3D scanner, but that could be an option too if we can get ahold of one and we can figure out how to operate it. Either way would work

**Comment by Kennaab** [comment]
this idea sounds very interesting to me. I think it would definitely be different to create the 3D models through blender and add them to the project. It'd create a unique and more personal approach to the project. Plus you're showing that you are versatile in different aspects of computer applications.

**Comment by ghbondar** [comment]
Greetings!
All of these projects sound exciting and possible, bearing a few things in mind:
- The classic piece of Mayan literature is the Popul Vuh. Unfortunately, there are no copies of the whole story in Mayan hieroglyphics, though there are many short passages on pottery. The images on the pottery are rather fun, kind of like comics, so that might be an interesting graphical interpretation, perhaps with the translation of a glyph popping-up on mouse-over. Presumably, you would be working with material that has already been translated. Ample XML mark-up opportunities!

-  The regional mapping is interesting because, over the 2000 years or so of prehistoric Mayan civilization, there are shift as dozens of sites are abandoned and new ones established elsewhere. While this project would be practical at a large scale, because there are hundreds of sites, a temple-by-temple, pyramid-by-pyramid level of mapping would be probably more than you would want to do.

- This scale of mapping would be possible for a single site, to use a game engine or sketch-up or other CAD or GIS software to model/reconstruct.

Here are some links:
http://www.latinamericanstudies.org/tikal-maps.htm
https://www.latinamericanstudies.org/copan-maps.htm
https://ezaccess.libraries.psu.edu/login?url=https://www.jstor.org/stable/26307335
https://www.latinamericanstudies.org/palenque-maps.htm
http://www.latinamericanstudies.org/chichen-itza-maps.htm
http://www.mesoweb.com/chichen/resources/map/SChome.html

Enjoy!!

**Comment by ebeshero** [comment]
Thanks @ghbondar ! These leads will help a lot to organize a manageable and super interesting project this semester!

**Comment by am0eba-byte** [comment]
Thanks so much @ghbondar these are some top notch things to consider and resources! Extremely helpful. If this project is a go, we will be sure to keep you updated on the developments! Also, would it be possible for us to take photos of any of the Mayan relics you have on-hand to turn into 3D models using photogrammetry? (Of course we would take the upmost caution while handling these items if you're okay with us photographing them!)

**Comment by ghbondar** [comment]
While I wish I have more Mayan things for you to scan, I have only two (replicas) that are Mayan. However, more objects might be on display in museums in Pittsburgh, Cleveland, Buffalo, etc., and depending on the display, it might be possible to take enough photos to do a 3D model of an object using photogrammetry. 

Actually, the Cleveland Museum of Art has many Mayan objects in their collections, but who knows if they are on display...
https://www.clevelandart.org/art/collection/search?i=1&search=maya

**Comment by ebeshero** [comment]
@ghbondar and I were chatting about the project and thinking of some areas you may just want to know about as you're digging into a Mayan digital project on images and texts. Here are some recommended topics to read and explore:

### Mayan writing (what we know about it / where we find it):

Here's a really good article to orient you on ancient Mayan writing, how happened to it, and how it's found on engravings / pottery. This also shows you how the Mayan pictures (hieroglyphics or logograms) make parts of words:

https://www.bl.uk/history-of-writing/articles/ancient-maya-writing

Okay, you're going to hear about codices (plural for codex): The ancient Mayans made "books" out of mulberry-bark paper that apparently fanned out like accordions. And the logograms/hieroglyphics in those are often compared to what appears carved or painted on the Mayan ceramics. And Mayan creation narratives show up *on* the ceramics in what they call "codex style" b/c they look like the kind of script you see on the codices. 

Okay: so they had picture-based text where pictures represented parts of words. But they *also* had illustrations, and lots of interesting mythological depictions of gods. Some of the pictures show dynamic movement maybe something like we show in comic books, as @ghbondar mentions! Here is a really good, illustrated short article to show you all that.  Keep a weather eye out for the rain/storm god, Chahk!  

Creation Narratives on Ancient Maya Codex-Style Ceramics in the Metropolitan Museum: 
https://www.journals.uchicago.edu/doi/full/10.1086/691105?journalCode=met#_i23

(This article made me wonder if it might be fun to animate some of the images of Chahk and jaguar. . .)

### Flattening 3D into 2D "rollout" photos 
One thing scholars do to read Mayan writings and illustrations off the pottery is to *undo* their 3D dimensions by taking lots of pictures of every surface, to **roll them out** so you can read them more clearly all together as flat. The article above shows that, but here (below) are some more resources full of detailed images and "rollouts".  NOTE the images here are marked in public domain so you can totally work your ways with them: 

Mayan Vessel: Mythological Scene (7th - 8th c., housed at the Met Museum in NYC): 
https://www.metmuseum.org/art/collection/search/310364

Read about the mysterious Mayan artist they call "Metropolitan Painter" b/c they think the same person did a lot of these super elaborate scenes.

**Comment by am0eba-byte** [comment]
@ghbondar @ebeshero WOW These resources and idea-starters are marvelous! I'm going to start a Google Doc to jot down and brainstorm all the different possibilities our project team has in exploring these many methods of digitizing the Mayans, along with the provided resources you so generously provided. Thank you both so much, this project is going to be an adventure! :D
