### ISSUE TITLE
Project Proposal: Blues Part Two

### ISSUE THREAD

**Issue by am0eba-byte** [newtfire/digitProjectDesign-Hub#60]
Being on this project team would involve filling in the gaps in the blues song data pool of [an existing project!](https://am0eba-byte.github.io/blues/index.html) 

To do this, we would begin by finding sources of blues song lyric texts that are not already in the current collection (all of Lightnin' Hopkins, Taj Mahal, and Buddy Guy's songs, for example), then scraping the songs off the web into individual song lyric files. Scraping the text off the sites will be pretty easy since we already have functional python scripts to do the job, we may just need to tweak it a tiny bit. 

We would then use REGEX to wrap code around the song metadata and lyric text in all of the files en masse, and create some neat data visualizations and interactive graphics with Cytoscape, Python, XQuery, and SVG to replace the old ones. 

We could also create new visualizations based on the updated lyric data collection to create a clearer and more representative analysis of the blues genre.

**Comment by amw6765** [comment]
I think this would be a great continuation of the project you and your group did last semester. It gave an interactive insight into the connections and differences between different popular blues songs. As a lay person to the genre of blues, last semesters project helped me learn quite a bit about the genre. I would only assume that this would continue to inform peers and others about this as well. There is definitely a lot more that you could do with this project for this semester. It would be interesting to maybe see a visualization of a map that shows where each of these songs were written. It could give people a good look at what areas in the US are most common for blues song writing!

**Comment by amw6765** [comment]
wow you think I woulda seen the big green "Project-NONSTARTER" 🤦🏽‍♂️

**Comment by am0eba-byte** [comment]
@amw6765 Bahah I appreciate your comment anyways dude! I think your idea about making a visualization map is neat, I'll look into doing that whenever I get time to work on this project by myself (:
