### ISSUE TITLE
How to exit the GitBash text editor

### ISSUE THREAD

**Issue by JeremyF5737** [newtfire/digitProjectDesign-Hub#8]
When some users go through GitBash for the first time and type in their login credentials (usually when typing a commit message) they might be taken to a terminal that looks like this.

![image](https://user-images.githubusercontent.com/70647839/92500669-7b72d600-f1cb-11ea-8f6b-03e5f8e261d9.png)

This can be exited by using the following steps 

Step 1: press "i" on the keyboard. At the bottom of the screen there should be a line that says INSERT

![image](https://user-images.githubusercontent.com/70647839/92500902-d3a9d800-f1cb-11ea-9a75-66670c8f46ed.png)

Step 2: press the keys in the following order "Esc" then ":" (you can type this by using Shift+;) then press "w" , and finally "q" 

Step3: hit "Enter" and you will be back to the original editor. Keep in mind you can just press the up arrow key to find your original commit message and publish your message.

**Comment by ebeshero** [comment]
Thanks for posting this, @JeremyF5737 ! Here's a quick shorthand:
Press **I** to insert.  (make edits if you need to)
Exit with:
**[Esc]
:
w
q**
